import { MenuItem } from "./types";
import { drinkImages, foodImages } from "./images";

export const menuItems: MenuItem[] = [
  // Starters
  {
    id: "1",
    name: "Truffle Arancini",
    description: "Crispy risotto balls with black truffle and parmesan, served with truffle aioli",
    price: 1200,
    category: "starters",
    spiceLevel: "mild",
    isVegetarian: true,
    image: foodImages.elegantlyfriedfood1,
  },
  {
    id: "2",
    name: "Wagyu Beef Carpaccio",
    description: "Thinly sliced premium wagyu beef with rocket, capers, and aged balsamic",
    price: 1800,
    category: "starters",
    spiceLevel: "mild",
    isVegetarian: false,
    image: foodImages.friedmeatcuisine,
  },
  {
    id: "3",
    name: "Lobster Bisque",
    description: "Rich and creamy lobster soup with cognac and fresh herbs",
    price: 1500,
    category: "starters",
    spiceLevel: "mild",
    isVegetarian: false,
    image: foodImages.seafood,
  },
  {
    id: "4",
    name: "Burrata Caprese",
    description: "Fresh burrata with heirloom tomatoes, basil oil, and aged balsamic",
    price: 1100,
    category: "starters",
    spiceLevel: "mild",
    isVegetarian: true,
    image: foodImages.elegantlyfriedfood2,
  },
  {
    id: "5",
    name: "Crispy Calamari",
    description: "Fresh calamari rings with spicy marinara and lemon aioli",
    price: 1300,
    category: "starters",
    spiceLevel: "medium",
    isVegetarian: false,
    image: foodImages.seafood,
  },
  {
    id: "6",
    name: "Truffle Bruschetta",
    description: "Artisan bread with truffle butter, wild mushrooms, and parmesan",
    price: 950,
    category: "starters",
    spiceLevel: "mild",
    isVegetarian: true,
    image: foodImages.elegantlyfriedfood1,
  },

  // Mains
  {
    id: "7",
    name: "Wagyu Beef Tenderloin",
    description: "Premium wagyu tenderloin with truffle mashed potatoes and seasonal vegetables",
    price: 3500,
    category: "mains",
    spiceLevel: "mild",
    isVegetarian: false,
    image: foodImages.driedmeatcuisine,
  },
  {
    id: "8",
    name: "Pan-Seared Duck Breast",
    description: "Duck breast with cherry gastrique, wild rice, and roasted vegetables",
    price: 2800,
    category: "mains",
    spiceLevel: "mild",
    isVegetarian: false,
    image: foodImages.friedchicken,
  },
  {
    id: "9",
    name: "Truffle Risotto",
    description: "Creamy arborio rice with black truffle, wild mushrooms, and parmesan",
    price: 2200,
    category: "mains",
    spiceLevel: "mild",
    isVegetarian: true,
    image: foodImages.superservedlunch,
  },
  {
    id: "10",
    name: "Salmon en Papillote",
    description: "Atlantic salmon cooked in parchment with herbs, lemon, and seasonal vegetables",
    price: 2400,
    category: "mains",
    spiceLevel: "mild",
    isVegetarian: false,
    image: foodImages.seafood,
  },
  {
    id: "11",
    name: "Rack of Lamb",
    description: "Herb-crusted rack of lamb with ratatouille and rosemary jus",
    price: 3200,
    category: "mains",
    spiceLevel: "mild",
    isVegetarian: false,
    image: foodImages.driedmeatcuisine,
  },
  {
    id: "12",
    name: "Vegetarian Wellington",
    description: "Mushroom and spinach wellington with red wine reduction",
    price: 2000,
    category: "mains",
    spiceLevel: "mild",
    isVegetarian: true,
    image: foodImages.elegantlyfriedfood2,
  },

  // Desserts
  {
    id: "13",
    name: "Chocolate Soufflé",
    description: "Warm chocolate soufflé with vanilla ice cream and berry coulis",
    price: 800,
    category: "desserts",
    isVegetarian: true,
    image: foodImages.elegantlyfriedfood1,
  },
  {
    id: "14",
    name: "Tiramisu Classico",
    description: "Traditional Italian tiramisu with espresso and mascarpone",
    price: 700,
    category: "desserts",
    isVegetarian: true,
    image: foodImages.elegantlyfriedfood2,
  },
  {
    id: "15",
    name: "Crème Brûlée",
    description: "Classic vanilla crème brûlée with fresh berries",
    price: 650,
    category: "desserts",
    isVegetarian: true,
    image: foodImages.superservedlunch,
  },
  {
    id: "16",
    name: "Raspberry Cheesecake",
    description: "New York style cheesecake with raspberry coulis and fresh berries",
    price: 750,
    category: "desserts",
    isVegetarian: true,
    image: foodImages.elegantlyfriedfood1,
  },
  {
    id: "17",
    name: "Chocolate Lava Cake",
    description: "Warm chocolate cake with molten center, served with vanilla ice cream",
    price: 850,
    category: "desserts",
    isVegetarian: true,
    image: foodImages.elegantlyfriedfood2,
  },
  {
    id: "18",
    name: "Panna Cotta",
    description: "Silky vanilla panna cotta with mixed berry compote",
    price: 600,
    category: "desserts",
    isVegetarian: true,
    image: foodImages.superservedlunch,
  },

  // Drinks
  {
    id: "19",
    name: "Signature Cocktails",
    description: "Premium cocktails crafted by our mixologist",
    price: 1200,
    category: "drinks",
    isVegetarian: true,
    image: drinkImages.twoglassescombineddrink,
  },
  {
    id: "20",
    name: "Wine Selection",
    description: "Curated wine list featuring international and local selections",
    price: 800,
    category: "drinks",
    isVegetarian: true,
    image: drinkImages.chillingdrink,
  },
  {
    id: "21",
    name: "Artisan Coffee",
    description: "Premium coffee beans roasted locally with expert brewing",
    price: 400,
    category: "drinks",
    isVegetarian: true,
    image: drinkImages.premiumcoffee,
  },
  {
    id: "22",
    name: "Fresh Juices",
    description: "Cold-pressed juices with seasonal fruits and vegetables",
    price: 500,
    category: "drinks",
    isVegetarian: true,
    image: drinkImages.superjuicewithorange,
  },
  {
    id: "23",
    name: "Craft Beer",
    description: "Local and international craft beers on tap",
    price: 600,
    category: "drinks",
    isVegetarian: true,
    image: drinkImages.twoglassescombineddrink,
  },
  {
    id: "24",
    name: "Premium Tea",
    description: "Artisanal tea selection from around the world",
    price: 350,
    category: "drinks",
    isVegetarian: true,
    image: drinkImages.elegantcoffe,
  },
];

export const restaurantInfo = {
  name: "TAVO",
  tagline: "Savour The Difference",
  subtext: "Nairobi's address for delicacies — where world-class cuisine and white-glove service meet the standards of the city's finest hotels.",
  description: "Nestled in Rosslyn Square Luxury Mall, TAVO is Nairobi's destination for refined dining. From signature delicacies to intimate private suites, every detail is crafted for those who expect excellence.",
  address: {
    street: "Rosslyn Square Luxury Mall",
    city: "Redhill Road, Nairobi",
    country: "Kenya",
  },
  phone: "+254-729-575757",
  whatsapp: "+254-729-575757",
  email: "info@tavo.co.ke",
  hours: {
    mon_thu: "Mon - Thu: 10:00 AM - 11:00 PM",
    fri_sun: "Fri - Sun: 10:00 AM - 11:00 PM",
  },
  social: {
    instagram: "https://www.instagram.com/tavo_fusion?igsh=NnZzYTF6NTM5ZGhu",
    facebook: "https://facebook.com/tavo",
    google: "https://maps.app.goo.gl/fMbQjZMt66kRgVKs9",
    bolt: "https://food.bolt.eu/en-US/320/p/98628-tavo",
  },
};
